apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: os-monitor

bases:
  - ../../base

images:
  - name: registry.local.cloud:5000/os-monitor/api
    newTag: "9f0a810"
  - name: registry.local.cloud:5000/os-monitor/collector
    newTag: "latest"
  - name: registry.local.cloud:5000/os-monitor/dashboard
    newTag: "9f0a810"

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: os-monitor-api
