apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-dev

bases:
  - ../../base

images:
  - name: registry.local.cloud:5000/k8s-monitor/api
    newTag: "latest"
  - name: registry.local.cloud:5000/k8s-monitor/collector
    newTag: "latest"
  - name: registry.local.cloud:5000/k8s-monitor/dashboard
    newTag: "latest"

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
